# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="name-that-hash",
    version="1.7.2",
    description="The Modern Hash Identification System",
    python_requires="==3.*,>=3.6.0",
    author="brandon",
    author_email="brandon@skerritt.blog",
    license="GPL-3.0-or-later",
    entry_points={
        "console_scripts": [
            "nth = name_that_hash.runner:main",
            "name-that-hash = name_that_hash.runner:main",
        ]
    },
    packages=["name_that_hash"],
    package_dir={"": "."},
    package_data={},
    install_requires=["click==7.*,>=7.1.2", "rich<11.0,>=9.9"],
    extras_require={"dev": ["pytest==6.*,>=6.2.0"]},
)
